// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Landlord defines model for Landlord.
type Landlord struct {
	Email      string              `json:"email"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	IsArchived *time.Time          `json:"is_archived,omitempty"`
	Mobile     string              `json:"mobile"`
	Name       string              `json:"name"`
	Phone      string              `json:"phone"`
}

// Property defines model for Property.
type Property struct {
	AddressLine1  string              `json:"address_line_1"`
	AddressLine2  *string             `json:"address_line_2,omitempty"`
	Country       string              `json:"country"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IsArchived    *time.Time          `json:"is_archived,omitempty"`
	LandlordId    openapi_types.UUID  `json:"landlord_id"`
	ManagementFee float64             `json:"management_fee"`
	Postcode      string              `json:"postcode"`
	State         string              `json:"state"`
	Suburb        string              `json:"suburb"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Email             string              `json:"email"`
	EndDate           openapi_types.Date  `json:"end_date"`
	Id                *openapi_types.UUID `json:"id,omitempty"`
	IsArchived        *time.Time          `json:"is_archived,omitempty"`
	Mobile            string              `json:"mobile"`
	Name              string              `json:"name"`
	OriginalStartDate openapi_types.Date  `json:"original_start_date"`
	Phone             string              `json:"phone"`
	PropertyId        openapi_types.UUID  `json:"property_id"`
	StartDate         openapi_types.Date  `json:"start_date"`
	TerminationDate   *openapi_types.Date `json:"termination_date,omitempty"`
	TerminationReason *string             `json:"termination_reason,omitempty"`
	VacateDate        *openapi_types.Date `json:"vacate_date,omitempty"`
}

// LandlordsCreateJSONRequestBody defines body for LandlordsCreate for application/json ContentType.
type LandlordsCreateJSONRequestBody = Landlord

// LandlordsUpdateJSONRequestBody defines body for LandlordsUpdate for application/json ContentType.
type LandlordsUpdateJSONRequestBody = Landlord

// PropertiesCreateJSONRequestBody defines body for PropertiesCreate for application/json ContentType.
type PropertiesCreateJSONRequestBody = Property

// PropertiesUpdateJSONRequestBody defines body for PropertiesUpdate for application/json ContentType.
type PropertiesUpdateJSONRequestBody = Property

// TenantsCreateJSONRequestBody defines body for TenantsCreate for application/json ContentType.
type TenantsCreateJSONRequestBody = Tenant

// TenantsUpdateJSONRequestBody defines body for TenantsUpdate for application/json ContentType.
type TenantsUpdateJSONRequestBody = Tenant

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /landlords)
	LandlordsList(w http.ResponseWriter, r *http.Request)

	// (POST /landlords)
	LandlordsCreate(w http.ResponseWriter, r *http.Request)

	// (DELETE /landlords/{id})
	LandlordsArchive(w http.ResponseWriter, r *http.Request, id string)

	// (GET /landlords/{id})
	LandlordsGet(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /landlords/{id})
	LandlordsUpdate(w http.ResponseWriter, r *http.Request, id string)

	// (GET /properties)
	PropertiesList(w http.ResponseWriter, r *http.Request)

	// (POST /properties)
	PropertiesCreate(w http.ResponseWriter, r *http.Request)

	// (DELETE /properties/{id})
	PropertiesArchive(w http.ResponseWriter, r *http.Request, id string)

	// (GET /properties/{id})
	PropertiesGet(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /properties/{id})
	PropertiesUpdate(w http.ResponseWriter, r *http.Request, id string)

	// (GET /tenants)
	TenantsList(w http.ResponseWriter, r *http.Request)

	// (POST /tenants)
	TenantsCreate(w http.ResponseWriter, r *http.Request)

	// (DELETE /tenants/{id})
	TenantsArchive(w http.ResponseWriter, r *http.Request, id string)

	// (GET /tenants/{id})
	TenantsGet(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /tenants/{id})
	TenantsUpdate(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LandlordsList operation middleware
func (siw *ServerInterfaceWrapper) LandlordsList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LandlordsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LandlordsCreate operation middleware
func (siw *ServerInterfaceWrapper) LandlordsCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LandlordsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LandlordsArchive operation middleware
func (siw *ServerInterfaceWrapper) LandlordsArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LandlordsArchive(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LandlordsGet operation middleware
func (siw *ServerInterfaceWrapper) LandlordsGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LandlordsGet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LandlordsUpdate operation middleware
func (siw *ServerInterfaceWrapper) LandlordsUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LandlordsUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PropertiesList operation middleware
func (siw *ServerInterfaceWrapper) PropertiesList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PropertiesList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PropertiesCreate operation middleware
func (siw *ServerInterfaceWrapper) PropertiesCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PropertiesCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PropertiesArchive operation middleware
func (siw *ServerInterfaceWrapper) PropertiesArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PropertiesArchive(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PropertiesGet operation middleware
func (siw *ServerInterfaceWrapper) PropertiesGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PropertiesGet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PropertiesUpdate operation middleware
func (siw *ServerInterfaceWrapper) PropertiesUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PropertiesUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TenantsList operation middleware
func (siw *ServerInterfaceWrapper) TenantsList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TenantsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TenantsCreate operation middleware
func (siw *ServerInterfaceWrapper) TenantsCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TenantsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TenantsArchive operation middleware
func (siw *ServerInterfaceWrapper) TenantsArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TenantsArchive(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TenantsGet operation middleware
func (siw *ServerInterfaceWrapper) TenantsGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TenantsGet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TenantsUpdate operation middleware
func (siw *ServerInterfaceWrapper) TenantsUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TenantsUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/landlords", wrapper.LandlordsList).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landlords", wrapper.LandlordsCreate).Methods("POST")

	r.HandleFunc(options.BaseURL+"/landlords/{id}", wrapper.LandlordsArchive).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/landlords/{id}", wrapper.LandlordsGet).Methods("GET")

	r.HandleFunc(options.BaseURL+"/landlords/{id}", wrapper.LandlordsUpdate).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/properties", wrapper.PropertiesList).Methods("GET")

	r.HandleFunc(options.BaseURL+"/properties", wrapper.PropertiesCreate).Methods("POST")

	r.HandleFunc(options.BaseURL+"/properties/{id}", wrapper.PropertiesArchive).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/properties/{id}", wrapper.PropertiesGet).Methods("GET")

	r.HandleFunc(options.BaseURL+"/properties/{id}", wrapper.PropertiesUpdate).Methods("PUT")

	r.HandleFunc(options.BaseURL+"/tenants", wrapper.TenantsList).Methods("GET")

	r.HandleFunc(options.BaseURL+"/tenants", wrapper.TenantsCreate).Methods("POST")

	r.HandleFunc(options.BaseURL+"/tenants/{id}", wrapper.TenantsArchive).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/tenants/{id}", wrapper.TenantsGet).Methods("GET")

	r.HandleFunc(options.BaseURL+"/tenants/{id}", wrapper.TenantsUpdate).Methods("PUT")

	return r
}
